version: "3"

services:
  jenkins:
    build: .
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    ports:
      - 8080
      - 50000:50000
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - VIRTUAL_HOST=clara-build.clear-it.de
      - VIRTUAL_PORT=8080

networks:
  default:
    external:
      name: nginx-proxy
